/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositQueueLib } from "./DepositQueueLib";
export type { DepositTreeLib } from "./DepositTreeLib";
