/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IL1ScrollMessenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IL1ScrollMessenger__factory>;
    getContractFactory(
      name: "IL2ScrollMessenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IL2ScrollMessenger__factory>;
    getContractFactory(
      name: "IScrollMessenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IScrollMessenger__factory>;
    getContractFactory(
      name: "Deposit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Deposit__factory>;
    getContractFactory(
      name: "Int0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Int0__factory>;
    getContractFactory(
      name: "IInt0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInt0__factory>;
    getContractFactory(
      name: "IINTMAXToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IINTMAXToken__factory>;
    getContractFactory(
      name: "IMinterV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterV1__factory>;
    getContractFactory(
      name: "IPlonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPlonkVerifier__factory>;
    getContractFactory(
      name: "IRollup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRollup__factory>;
    getContractFactory(
      name: "MinterV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterV0__factory>;
    getContractFactory(
      name: "MinterV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterV1__factory>;
    getContractFactory(
      name: "MintVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintVerifier__factory>;
    getContractFactory(
      name: "PlonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PlonkVerifier__factory>;
    getContractFactory(
      name: "ClaimPlonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClaimPlonkVerifier__factory>;
    getContractFactory(
      name: "WithdrawalPlonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WithdrawalPlonkVerifier__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IL1ScrollMessenger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IL1ScrollMessenger>;
    getContractAt(
      name: "IL2ScrollMessenger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IL2ScrollMessenger>;
    getContractAt(
      name: "IScrollMessenger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IScrollMessenger>;
    getContractAt(
      name: "Deposit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Deposit>;
    getContractAt(
      name: "Int0",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Int0>;
    getContractAt(
      name: "IInt0",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInt0>;
    getContractAt(
      name: "IINTMAXToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IINTMAXToken>;
    getContractAt(
      name: "IMinterV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMinterV1>;
    getContractAt(
      name: "IPlonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPlonkVerifier>;
    getContractAt(
      name: "IRollup",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRollup>;
    getContractAt(
      name: "MinterV0",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinterV0>;
    getContractAt(
      name: "MinterV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinterV1>;
    getContractAt(
      name: "MintVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MintVerifier>;
    getContractAt(
      name: "PlonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PlonkVerifier>;
    getContractAt(
      name: "ClaimPlonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ClaimPlonkVerifier>;
    getContractAt(
      name: "WithdrawalPlonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WithdrawalPlonkVerifier>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IL1ScrollMessenger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL1ScrollMessenger>;
    deployContract(
      name: "IL2ScrollMessenger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL2ScrollMessenger>;
    deployContract(
      name: "IScrollMessenger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IScrollMessenger>;
    deployContract(
      name: "Deposit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Deposit>;
    deployContract(
      name: "Int0",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Int0>;
    deployContract(
      name: "IInt0",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInt0>;
    deployContract(
      name: "IINTMAXToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IINTMAXToken>;
    deployContract(
      name: "IMinterV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMinterV1>;
    deployContract(
      name: "IPlonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPlonkVerifier>;
    deployContract(
      name: "IRollup",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRollup>;
    deployContract(
      name: "MinterV0",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinterV0>;
    deployContract(
      name: "MinterV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinterV1>;
    deployContract(
      name: "MintVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintVerifier>;
    deployContract(
      name: "PlonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PlonkVerifier>;
    deployContract(
      name: "ClaimPlonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimPlonkVerifier>;
    deployContract(
      name: "WithdrawalPlonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WithdrawalPlonkVerifier>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IL1ScrollMessenger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL1ScrollMessenger>;
    deployContract(
      name: "IL2ScrollMessenger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL2ScrollMessenger>;
    deployContract(
      name: "IScrollMessenger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IScrollMessenger>;
    deployContract(
      name: "Deposit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Deposit>;
    deployContract(
      name: "Int0",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Int0>;
    deployContract(
      name: "IInt0",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInt0>;
    deployContract(
      name: "IINTMAXToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IINTMAXToken>;
    deployContract(
      name: "IMinterV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMinterV1>;
    deployContract(
      name: "IPlonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPlonkVerifier>;
    deployContract(
      name: "IRollup",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRollup>;
    deployContract(
      name: "MinterV0",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinterV0>;
    deployContract(
      name: "MinterV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinterV1>;
    deployContract(
      name: "MintVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintVerifier>;
    deployContract(
      name: "PlonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PlonkVerifier>;
    deployContract(
      name: "ClaimPlonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimPlonkVerifier>;
    deployContract(
      name: "WithdrawalPlonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WithdrawalPlonkVerifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
