/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
export type { Deposit } from "./Deposit";
export type { IINTMAXToken } from "./IINTMAXToken";
export type { IPlonkVerifier } from "./IPlonkVerifier";
export type { Int0 } from "./Int0";
export type { Minter } from "./Minter";
