/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  DepositQueueLib,
  DepositQueueLibInterface,
} from "../../../contracts/lib/DepositQueueLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "upToDepositId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastDepositId",
        type: "uint256",
      },
    ],
    name: "TriedAnalyzeNotExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rejectIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "front",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "upToDepositId",
        type: "uint256",
      },
    ],
    name: "TriedToRejectOutOfRange",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e403bec28376d7b133ffc91fbd4c63b48238c9f4a5c7ec564e1f5af0f1bd732464736f6c63430008180033";

type DepositQueueLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DepositQueueLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DepositQueueLib__factory extends ContractFactory {
  constructor(...args: DepositQueueLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DepositQueueLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DepositQueueLib__factory {
    return super.connect(runner) as DepositQueueLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DepositQueueLibInterface {
    return new Interface(_abi) as DepositQueueLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DepositQueueLib {
    return new Contract(address, _abi, runner) as unknown as DepositQueueLib;
  }
}
