/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IINTMAXToken } from "./IINTMAXToken";
export type { IInt0 } from "./IInt0";
export type { IPlonkVerifier } from "./IPlonkVerifier";
export type { IRollup } from "./IRollup";
