/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInt0,
  IInt0Interface,
} from "../../../contracts/interfaces/IInt0";

const _abi = [
  {
    inputs: [],
    name: "getDepositRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IInt0__factory {
  static readonly abi = _abi;
  static createInterface(): IInt0Interface {
    return new Interface(_abi) as IInt0Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IInt0 {
    return new Contract(address, _abi, runner) as unknown as IInt0;
  }
}
