/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInt1,
  IInt1Interface,
} from "../../../contracts/interfaces/IInt1";

const _abi = [
  {
    inputs: [],
    name: "TriedToDepositZero",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "depositIndex",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "depositHash",
        type: "bytes32",
      },
    ],
    name: "DepositLeafInserted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "depositId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "recipientSaltHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "tokenIndex",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositedAt",
        type: "uint256",
      },
    ],
    name: "Deposited",
    type: "event",
  },
] as const;

export class IInt1__factory {
  static readonly abi = _abi;
  static createInterface(): IInt1Interface {
    return new Interface(_abi) as IInt1Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IInt1 {
    return new Contract(address, _abi, runner) as unknown as IInt1;
  }
}
